name: docker image testing

on:
  push:
    branches:
      - master
      - mseed
  pull_request:
    branches:
      - master
      - mseed

env:
  AWSACCESSKEYID: ${{ secrets.AWSACCESSKEYID}}
  AWSSECRETACCESSKEY: ${{ secrets.AWSSECRETACCESSKEY }}
  BUCKET_TYPE: ${{ secrets.BUCKET_TYPE}}
  NODE_NAME: ${{ secrets.NODE_NAME }}
  NODE_TYPE: ${{ secrets.NODE_TYPE }}
  
jobs:
  Docker-tests:
    runs-on: ubuntu-20.04
    steps:  
      - uses: actions/checkout@v3
      - name: build base image
        run: cd base/amd64 && ./buildamdbase.sh
      - name: start containers
        run: ls && cd mseed && docker-compose up --build
      - name: clean up containers
        run: docker-compose down
        
