name: docker image testing

on:
  push:
    branches:
      - master
      - mseed
  pull_request:
    branches:
      - master
      - mseed

job:
  Docker tests:
    runs-on: ubuntu 20.04
    steps:      
      - name: start containers
        run: cd mseed/ && docker-compose up --build
      - name: clean up containers
        run: docker-compose down
        